### PR TITLE
Code style: formatting + consistency

### PR DESCRIPTION
**Pull request by kfrn**
* Autoformatted to PEP-8
* Normalised to double-quoted strings (PEP-8 [doesn't give a standard](https://www.python.org/dev/peps/pep-0008/#string-quotes), so I picked the more common one)
* Explanatory comments moved inside functions (since the autoformatter pulls them several lines above).

I also updated the `RESOLUTIONS` comment, which I forgot to change in a3c95c9066d19ac2b3935a621481fd3441a656b8.

### Note

There are no actual code changes here, it's just stylistic stuff. Hopefully you don't mind! I think it's nice to have it all consistent, but this also allows me to turn the "format on save" option back on in my code editor. :-) (Code formatting? Make a robot do it!)

### CODE REVIEW

**Comment by kieranjol** [comment]
I usually check code with pylint and manually change where necessary cos I
am paranoid but regardless, +100 for following pep-08 more! This was a PR I
was going to make myself! You're the best!

**Comment by kfrn** [comment]
I think I'm coming across as way more of a PEP-8 guru than I actually am, haha! I've only looked up a few specifics in there. The credit really goes to my code editor (I use Atom) and its beautifiers - the Python formatter uses `autopep8` (checks out to me) by default, so I didn't even have to set anything up. Boom, done. 

I haven't used `pylint`, but I imagine it's analytic as well as stylistic?

And I just realised that I didn't format the other scripts too - maybe one of you wants to?

**Comment by digitensions** [comment]
Sorry I totally missed this PR, not used to being this side of the line. Many thanks both :)

**Comment by kfrn** [comment]
Cool! I've got some further ideas for refactors too, if you're interested @digitensions 😃

**Comment by digitensions** [comment]
Yes please Katherine! I’d be pleased to see your changes :)

**Pull request merged**
